WebAppBase/WebAppBase/Models/Chart/ChartJSModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WebAppBase.Models.Chart
{
    public class BarConfig
    {
        public string type { get; set; }
        public BarChartData data { get; set; }
        public Options options { get; set; }
    }
    public class BarChartData
    {
        public string[] labels { get; set; }
        public BarChartDataSetBase[] datasets { get; set; }
    }

    public class BarChartDataSetBase
    {
        public string label { get; set; }
        public string backgroundColor { get; set; }
        public string borderColor { get; set; }
        public string pointBorderColor { get; set; }
        public string pointBackgroundColor { get; set; }
        public int pointBorderWidth { get; set; }
        public string yAxisID { get; set; }
        public int lineTension { get; set; }
        public bool fill { get; set; }
        public string DataKey { get; set; }
    }

    public class BarChartDataSet : BarChartDataSetBase
    {
        public decimal[] data { get; set; }
    }

    //public class BarChartDataSetXY : BarChartDataSetBase
    //{
    //    public ChartXYData[] data { get; set; }
    //}

    public class Options
    {
        public bool responsive { get; set; }
        public string hoverMode { get; set; }
        public int hoverAnimationDuration { get; set; }
        public bool stacked { get; set; }

        public Title title { get; set; }
        public Scales scales { get; set; }
        public Zoom zoom { get; set; }
    }

    public class Title
    {
        public bool display { get; set; }
        public string text { get; set; }
    }

    public class Scales
    {
        public XAxe[] xAxes { get; set; }
        public YAxe[] yAxes { get; set; }
    }

    public class XAxe
    {
        public string type { get; set; }
        public XAxeTime time { get; set; }

    }

    public class XAxeTime
    {
        public string unit { get; set; }
        public int unitStepSize { get; set; }
        public Dictionary<string, string> displayFormats { get; set; }
    }

    public class YAxe
    {
        public string type { get; set; }
        public bool display { get; set; }
        public string position { get; set; }
        public ScaleLabel scaleLabel { get; set; }
        public string id { get; set; }
        public GridLines gridLines { get; set; }
        public YAxesTicks ticks { get; set; }
    }

    public class ScaleLabel
    {
        public bool display { get; set; }
        public string labelString { get; set; }
    }

    public class GridLines
    {
        public bool drawOnChartArea { get; set; }
    }

    public class YAxesTicks
    {
        public decimal max { get; set; }
        public decimal min { get; set; }
    }

    public class Zoom
    {
        public bool enabled { get; set; }
        public bool drag { get; set; }
        public string mode { get; set; }
        public Limits limits { get; set; }

        public Zoom()
        {
            enabled = true;
            drag = true;
            mode = "x";
            limits = new Limits() { max = 10f, min = 0.5f };
        }
    }

    public class Limits
    {
        public float max { get; set; }
        public float min { get; set; }
    }

    //public class ChartXYData
    //{
    //    public string x { get; set; }
    //    public decimal y { get; set; }
    //}

}

WebAppBase/WebAppBase/Models/Chart/ChartTargetModel.cs
using SharedUtilitys.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WebAppBase.Models.Chart
{
    public class ChartTargetModel : BaseModel
    {
        public static List<string> ChartColors { get; private set; }
        public string OrganizationID { get; set; }
        public string Title { get; set; }
        public string RedirectController { get; set; }
        public string RedirectAction { get; set; }
        public object RouteValues { get; set; }

        public string[] ChartTypes { get; set; }

        public string XAxesType { get; set; }
        public string XAxesTimeUnit { get; set; }
        public int XAxesUnitStepSize { get; set; }
        public Dictionary<string,string> XAxesDisplayFormats { get; set; }

        public bool ZoomEnable { get; set; }

        public List<string> Labels { get; set; }
        public List<Dictionary<string, string>> ChartYAxisLables { get; set; }
        public List<Dictionary<string, List<decimal>>> ChartYAxisValues { get; set; }

        public string RefUrl { get; set; }

        static ChartTargetModel()
        {
            ChartColors = new List<string>();
            ChartColors.Add("rgba(0, 152, 254, 1)");
            ChartColors.Add("rgba(221, 8, 0, 1)");
            ChartColors.Add("rgba(255, 170, 102, 1)");
            ChartColors.Add("rgba(91, 193, 70, 1)");
            ChartColors.Add("rgba(0, 0, 0, 1)");
        }

        public ChartTargetModel()
        {
            ChartTypes = new[] { "line", "bar" };
            XAxesType = "time";
            XAxesTimeUnit = "month";
            XAxesUnitStepSize = 1;
            XAxesDisplayFormats = new Dictionary<string, string>();
            XAxesDisplayFormats.Add("month", "YYYY-MM");
            Labels = new List<string>();
            ChartYAxisLables = new List<Dictionary<string, string>>();
            ChartYAxisValues = new List<Dictionary<string, List<decimal>>>();
            ZoomEnable = true;
        }        

        public static decimal ToDecimal(int? intValue )
        {
            if (!intValue.HasValue)
            {
                return 0;
            }
            return intValue.Value;
        }

        public static decimal ToDecimal(decimal? decimalValue)
        {
            if (!decimalValue.HasValue)
            {
                return 0;
            }
            return decimalValue.Value;
        }

        public static decimal ToDecimal(object decimalValue)
        {
            decimal r;
            if (decimal.TryParse(string.Format("{0}", decimalValue).Replace("%",""), out r))
            {
                return r;
            }
            else
            {
                return 0;
            }
        }
    }

    public class ChartAxi
    {
        public int Index { get; set; }
        public string Key { get; set; }
    }
}

WebAppBase/WebAppBase/Controllers/ChartController.cs
using AspMvcLibrary.Attributes;
using WebAppBase.Configs;
using WebAppBase.Models.Chart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppBase.Controllers
{
    public class ChartController : Controller
    {
        public ActionResult Index()
        {
            var chartTargetModel = Session[SessionKeyConfig.ChartTargetModel] as ChartTargetModel;

            if (chartTargetModel == null)
            {
                return RedirectToAction("index", "home");
            }
            return View(chartTargetModel);
        }

        public ActionResult DeadReportChart()
        {
            var chartTargetModel = Session[SessionKeyConfig.ChartTargetModel] as ChartTargetModel;

            if (chartTargetModel == null)
            {
                return RedirectToAction("index", "home");
            }
            return View(chartTargetModel);
        }


        [HttpPost]
        public ActionResult InitChart(FormCollection formData)
        {
            var ChartAxis = new List<ChartAxi>();
            for (int i = 0; i < formData.Count / 2; i++)
            {
                var index = Convert.ToInt32(formData[i * 2]);
                var key = string.Format("{0}", formData[i * 2 + 1]);
                if (key.Equals("0"))
                {
                    continue;
                }
                ChartAxis.Add(new ChartAxi()
                {
                    Index = index,// Convert.ToInt32(formData[i * 2]),
                    Key = key// formData[i * 2 + 1]
                });
            }

            var barConfig = new BarConfig();
            var chartTargetModel = Session[SessionKeyConfig.ChartTargetModel] as ChartTargetModel;

            if (chartTargetModel == null)
            {
                barConfig.options.zoom.enabled = false;
                barConfig.options.zoom.drag = false;
                return Json(barConfig);
            }
            var axisLength = ChartAxis.Count;
            barConfig.type = chartTargetModel.ChartTypes[0];
            barConfig.data = new BarChartData();
            barConfig.data.labels = chartTargetModel.Labels.ToArray();
            barConfig.data.datasets = new BarChartDataSet[axisLength];
            for (int i = 0; i < axisLength; i++)
            {
                var key = ChartAxis[i].Key;
                var dataset = new BarChartDataSet();
                var yAxisLables = chartTargetModel.ChartYAxisLables[i];
                var listData = chartTargetModel.ChartYAxisValues[i];

                dataset.label = yAxisLables[key];
                dataset.backgroundColor = ChartTargetModel.ChartColors[i];
                dataset.borderColor = ChartTargetModel.ChartColors[i];
                dataset.pointBorderColor = ChartTargetModel.ChartColors[i];
                dataset.pointBackgroundColor = ChartTargetModel.ChartColors[i];
                dataset.pointBorderWidth = 1;
                dataset.yAxisID = string.Format("y-axis-{0}", i + 1);
                dataset.data = listData[key].ToArray();
                dataset.lineTension = 0;
                dataset.fill = false;
                dataset.DataKey = key;
                barConfig.data.datasets[i] = dataset;
            }

            barConfig.options = new Options();

            barConfig.options.responsive = true;
            barConfig.options.hoverMode = "index";
            barConfig.options.hoverAnimationDuration = 400;
            barConfig.options.stacked = false;
            barConfig.options.title = new Title()
            {
                display = false,
                text = chartTargetModel.Title
            };

            barConfig.options.scales = new Scales();
            if (!string.IsNullOrEmpty(chartTargetModel.XAxesType) && !string.IsNullOrEmpty(chartTargetModel.XAxesTimeUnit))
            {
                barConfig.options.scales.xAxes = new XAxe[1];
                var time = new XAxeTime()
                    {
                        unit = chartTargetModel.XAxesTimeUnit,
                        unitStepSize = chartTargetModel.XAxesUnitStepSize,
                        displayFormats = chartTargetModel.XAxesDisplayFormats
                    };
                barConfig.options.scales.xAxes[0] = new XAxe()
                {
                    type = chartTargetModel.XAxesType,
                    time = time,
                };
            }

            barConfig.options.scales.yAxes = new YAxe[axisLength];
            for (int i = 0; i < axisLength; i++)
            {
                var key = ChartAxis[i].Key;
                //var showAxis=(key.Equals("0") ? false : true);
                var yAxisLables = chartTargetModel.ChartYAxisLables[i];
                barConfig.options.scales.yAxes[i] = new YAxe();

                barConfig.options.scales.yAxes[i].type = "linear"; // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                barConfig.options.scales.yAxes[i].display = true;
                barConfig.options.scales.yAxes[i].scaleLabel = new ScaleLabel()
                {
                    display = true,
                    labelString = yAxisLables[key]
                };
                if (i % 2 == 0)
                {
                    barConfig.options.scales.yAxes[i].position = "left";
                }
                else
                {
                    barConfig.options.scales.yAxes[i].position = "right";
                }
                barConfig.options.scales.yAxes[i].id = string.Format("y-axis-{0}", i + 1);
                barConfig.options.scales.yAxes[i].gridLines = new GridLines()
                {
                    drawOnChartArea = i == 0
                };
                var listData = chartTargetModel.ChartYAxisValues[i];
                var dMax = listData[key].Max();
                if (dMax > 10)
                {
                    var len = Math.Floor(dMax).ToString().Length - 1;
                    var div = Convert.ToInt32(Math.Pow(10, len));
                    var ticksMax = (Math.Ceiling(dMax / div) * div);
                    if (ticksMax == dMax)
                    {
                        dMax = Convert.ToDecimal(Math.Ceiling(dMax / div) * div) * 1.25m;
                    }
                    else
                    {
                        dMax = ticksMax;
                    }
                }
                else
                {
                    dMax = Math.Ceiling(dMax * 1.25m);
                }
                dMax = Convert.ToDecimal(Math.Max(1, dMax));
                barConfig.options.scales.yAxes[i].ticks = new YAxesTicks()
                {
                    max = dMax
                };
            }
            barConfig.options.zoom = new Zoom();
            if (!chartTargetModel.ZoomEnable)
            {
                barConfig.options.zoom.enabled = false;
                barConfig.options.zoom.drag = false;
            }
            var r = new { barConfig = barConfig };
            return Json(r);
        }

        [HttpPost]
        public ActionResult GetChartData(string DataKey, int lineIdx)
        {
            var chartTargetModel = Session[SessionKeyConfig.ChartTargetModel] as ChartTargetModel;
            var dataLabel = chartTargetModel.ChartYAxisLables[0][DataKey];
            //var data = new List<ChartXYData>();
            //for (int i = 0; i < chartTargetModel.Labels.Count; i++)
            //{
            //    data.Add(new ChartXYData() { x = chartTargetModel.Labels[i], y = chartTargetModel.ChartYAxisValues[0][DataKey][i] });
            //}
            var data = chartTargetModel.ChartYAxisValues[0][DataKey];
            var idx = lineIdx % ChartTargetModel.ChartColors.Count;
            var key = DataKey;
            var dataset = new BarChartDataSet()
            {
                label = dataLabel,
                backgroundColor = ChartTargetModel.ChartColors[idx],
                borderColor = ChartTargetModel.ChartColors[idx],
                pointBorderColor = ChartTargetModel.ChartColors[idx],
                pointBackgroundColor = ChartTargetModel.ChartColors[idx],
                pointBorderWidth = 1,
                yAxisID = string.Format("y-axis-{0}", 0),
                data = data.ToArray(),
                lineTension = 0,
                fill = false,
                DataKey = DataKey
            };

            var dMax = data.Max();
            if (dMax > 10)
            {
                var len = Math.Floor(dMax).ToString().Length - 1;
                var div = Convert.ToInt32(Math.Pow(10, len));
                var ticksMax = (Math.Ceiling(dMax / div) * div);
                if (ticksMax == dMax)
                {
                    dMax = Convert.ToDecimal(Math.Ceiling(dMax / div) * div) * 1.25m;
                }
                else
                {
                    dMax = ticksMax;
                }
            }
            else
            {
                dMax = Math.Ceiling(dMax * 1.25m);
            }
            dMax = Convert.ToDecimal(Math.Max(1, dMax));

            var r = new { dataset = dataset, ticksMax = dMax };
            return Json(r);
        }

        [HttpPost]
        [ActionName("Index")]
        [SubmitCommand("back")]
        public ActionResult Back()
        {
            return _back();
        }

        [HttpPost]
        [ActionName("DeadReportChart")]
        [SubmitCommand("back")]
        public ActionResult Back2()
        {
            return _back();
        }

        public ActionResult _back()
        {
            var model = _getTarget();

WebAppBase/WebAppBase/Views/Chart/DeadReportChart.cshtml
@using WebAppBase.App_GlobalResources
@using System.Text
@model WebAppBase.Models.Chart.ChartTargetModel
@{
    ViewBag.Title = "ShowChartPage";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var labels= new  StringBuilder();
    foreach (var lab in Model.Labels)
    {
        if (labels.Length == 0)
        {
            labels.AppendFormat("'{0}'", lab);
        }
        else {
            labels.AppendFormat(",'{0}'", lab);
        }
    }
}

@section Style
{
    <style>
        canvas {
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }
    </style>

    <style type="text/css">
        .ChartAxis {
            width: 150px;
        }
    </style>
}


@section PrepareScriptBeforeRequestJS{
    <!--Chart.js-->
    <script src="@Url.Content("~/Contents/ChartJS/2.3.0/Chart.bundle.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Contents/ChartJS/hammer.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Contents/ChartJS/Chart.Zoom.js")" type="text/javascript"></script>
}

<h2>@Model.Title</h2>
@using (Html.BeginForm())
{
    <div style="margin-top:5px; text-align:right;">
        @if (Model.ZoomEnable)
        {
            <input id="btnResetZoom" name="btnResetZoom" style="width:80px;" type="button" value="リセット" />
        }
        @if (Model.ChartTypes.Length > 1 && Model.ChartTypes.Contains("line"))
        {
            <input id="btnGraphLineType" name="btnGraphLineType" class="btnBarType" bartype="line" style="width:80px;" type="button" value="折れ線" />
        }
        @if (Model.ChartTypes.Length > 1 && Model.ChartTypes.Contains("bar"))
        {
            <input id="btnGraphBarType" name="btnGraphBarType" class="btnBarType" bartype="bar" style="width:80px;" type="button" value="棒グラフ" />
        }
        <input id="btnBack" name="back" style="width:80px;" type="submit" value="戻る" />
    </div>

    <div>
        <table id="searchCondition" style="margin-top:10px; margin-bottom:10px;float:left;">
            <tr>
                <td valign="middle">
                    <span style="padding-right:10px;">生簀</span>
                </td>
                @if (Model.ChartYAxisLables.Count > 0)
                {
                    var i = 0;
                    var dic = Model.ChartYAxisLables[i];
                    var j = 0;
                    <td valign="middle">
                        <select id="@string.Format("ChartAxis{0}",i)" data-axisindex="@i" class="ChartAxis">
                            @foreach (var kv in dic)
                            {
                                if (j++ == i)
                                {
                                    <option value="@kv.Key" selected="selected">@kv.Value</option>
                                }
                                else
                                {
                                    <option value="@kv.Key">@kv.Value</option>
                                }
                            }
                        </select>
                    </td>
                    <td>
                        <input id="btnAddData" name="btnAddData" style="width:80px;margin-left:5px;" type="button"  value="追加" />
                    </td>
                    <td>
                        <input id="btnClear" name="btnClear" style="width:80px;margin-left:5px;" type="button" value="クリア" />
                    </td>
                }
            </tr>
        </table>
        <div style="clear:both;"></div>
    </div>
    <div style="width:100%;margin:0 auto;" id="canvasDiv">
        <canvas id="canvas"></canvas>
    </div>

}

@section Script{
    <script type="text/javascript">
        var ticksMax=1;
        var ticks;

    function adjustHeight() {
        //debugger;
        var windowHeight = getWindowHeight();
        var widdowWidth = $("#main").innerWidth();//  getWindowWidth();
        console.log(widdowWidth);
        var footerHeight = $("footer").outerHeight(true);
        var maxWidth = widdowWidth;
        var maxHeight = windowHeight - footerHeight - 200;
        if (maxWidth >= maxHeight * 2) {
            maxWidth = maxHeight * 2;
        }
        else {
            maxHeight =Math.min( maxHeight, maxWidth / 2);
        }

        $("#canvasDiv").css("height", maxHeight);
        $("#canvasDiv").css("width", maxWidth);
    };

    $(function () {

        adjustHeight();
        $(window).resize(adjustHeight);

        var ctx = document.getElementById("canvas").getContext("2d");
        window.myBar = new Chart(ctx, barConfig);

        $("select").wijcombobox();
        $("#btnResetZoom").click(resetZoom);
        $(".btnBarType").click(function () {
            setChartType($(this).attr('bartype'));
        });

        //$(".ChartAxis").change(InitChartData);
        $("#btnAddData").click(AddChartData);
        $("#btnClear").click(clearChartData)
        //InitChartData();
    });
    function resetZoom() {
        @if (!string.IsNullOrEmpty( Model.XAxesType) && !string.IsNullOrEmpty( Model.XAxesTimeUnit)){
            @Html.Raw(string.Format(@"
        window.myBar.scales['x-axis-0'].options.time.unitStepSize ={0};", Model.XAxesUnitStepSize))
        }        
        window.myBar.resetZoom();
    }

    function clearChartData()
    {
        barChartData.datasets.length=0;
        tickMax=1;
        barConfig.options.scales['yAxes'][0].ticks.max=tickMax;
        window.myBar.update();
    }

    function setChartType(type) {
        if (barConfig.type == type)
        {
            return;
        }
        barConfig.type = type;
        window.myBar.resetZoom();
    }

    function InitChartData() {
        //debugger;
        var url = '@Url.Action("InitChart", "Chart")';
        var axis = new Array();
        for (var i = 0; i < $(".ChartAxis").length; i++) {
            var cmb = $($(".ChartAxis")[i]);
            var obj = { Index: cmb.attr("data-axisindex"), Key: cmb.val() };
            axis.push(obj);
        }
        var postData = { ChartAxis: axis };
        $.post(url, postData, function (r) {
            //debugger;
            barChartData.labels = r.barConfig.data.labels;
            //barChartData.datasets = r.barConfig.data.datasets;

            //barOptions.responsive = r.barConfig.options.responsive;
            //barOptions.hoverMode = r.barConfig.options.hoverMode;
            //barOptions.hoverAnimationDuration = r.barConfig.options.hoverAnimationDuration;
            //barOptions.stacked = r.barConfig.options.stacked;

            //barOptions.title = r.barConfig.options.title;
            //barOptions.scales = {};
            //if (r.barConfig.options.scales.xAxes != null)
            //{
            //    barOptions.scales.xAxes = r.barConfig.options.scales.xAxes;
            //}
            //barOptions.scales.yAxes = r.barConfig.options.scales.yAxes;
            //if (r.barConfig.options.zoom != null) {
            //    barOptions.zoom = r.barConfig.options.zoom;
            //}

            //barConfig.type = r.barConfig.type;
            barConfig.data = barChartData;
            //barConfig.options = barOptions;

            window.myBar.destroy();
            var ctx = document.getElementById("canvas").getContext("2d");
            window.myBar = new Chart(ctx, barConfig);
        });
    }

        function AddChartData() {
            //debugger;
            var cmb = $("#ChartAxis0");
            var DataKey = cmb.val();
            var exists = false;
            for (var i = 0; i < barChartData.datasets.length; i++) {
                var ds = barChartData.datasets[i];
                if (ds.DataKey == DataKey)
                {
                    exists = true;
                    break;
                }
            }
            if (exists) {
                return;
            }

            var url = '@Url.Action("GetChartData", "Chart")';
            var postData = { DataKey: cmb.val(), lineIdx: barChartData.datasets.length };
            $.post(url, postData, function (r) {
                //debugger;
                barChartData.datasets.push(r.dataset);
                barConfig.data = barChartData;
                tickMax= barConfig.options.scales['yAxes'][0].ticks.max || 1;
                tickMax=Math.max(tickMax, r.ticksMax);
                barConfig.options.scales['yAxes'][0].ticks.max=tickMax;
                //window.myBar.scales['y-axis-0'].max=tickMax;
                console.log(barConfig.options.scales['yAxes'][0].ticks.max);
                window.myBar.update();
            });
        }


    </script>
    <script>
    var randomScalingFactor = function () {
        return Math.abs((Math.random() > 0.5 ? 1.0 : -1.0) * Math.round(Math.random() * 100));
    };
    var randomColorFactor = function () {
        return Math.round(Math.random() * 255);
    };
    var randomColor = function () {
        return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',.7)';
    };

    var barChartData = {
        labels: [@Html.Raw(labels)],
        datasets: []
    };

    var barOptions = {
        responsive: true,
        hoverMode: 'index',
        hoverAnimationDuration: 400,
        stacked: false,
        onClick: function (o, e) {
            if (window.myBar.scales["x-axis-0"].scaleSizeInUnits != null) {
                console.log(window.myBar.scales["x-axis-0"].scaleSizeInUnits);
                window.myBar.scales["x-axis-0"].options.time.unitStepSize = parseInt(Math.max(1, window.myBar.scales["x-axis-0"].scaleSizeInUnits / 10));
                window.myBar.update(0);
            }
        },
        title: {
            display: false,
            text: "@Model.Title"
        },
        scales: {
            xAxes: [{
                type: "time",
                time: {
                    unit: 'day',
                    unitStepSize: @Model.XAxesUnitStepSize,
                    displayFormats: {
                        day: 'YYYY/MM/DD'
                    }
                },
                ticks: {
                    maxRotation: 60,
                }
            }],
            yAxes: [{
                type: "linear", // only linear but allow scale type registration. This allows extensions to exist solely for log scale for instance
                display: true,
                position: "left",
                ticks:{                    
                    min:0
                },
                scaleLabel: {
                    display: true,
                    labelString: '斃死数'
                },
                gridLines:{
                    drawOnChartArea:true
                },
                id: "y-axis-0",
            }],
        },
        zoom: {
            enabled: true,
            drag: true,
            mode: 'x',
            limits: {
                max: 10,
                min: 0.5
            }
        },
        legend: {
            display: true,
            labels: {
                fontFamily: 'メイリオ',
                fontSize: 14
            }
        }
    };

    var barConfig={
        type: '@Model.ChartTypes[0]',
        data: barChartData,
        options: barOptions
    };

    </script>
}