WebAppBase/WebAppBase/Models/Sorts/SortListModel.cs
using System;
using System.Collections.Generic;
using SharedUtilitys.DataBases;
using WebAppBase.Models.Base;
using PacificSystem.Utility;

namespace WebAppBase.Models.Sorts
{
    public class SortListModel
    {
        public List<SortModel> Items { get; set; }

        public SortListModel()
        {
            Items = new List<SortModel>();
        }

        public SortListModel(SortTargetModel model)
        {
            Items = new List<SortModel>();

            if (model.SortItems != null)
            {
                if (model.SortItems.Count > 0)
                {
                    var firstItem = model.SortItems[0];
                    var type = firstItem.GetType();
                    var IdColumnPropInfo = type.GetProperty(model.IdColumn);
                    var DisplayNoColumnPropInfo = type.GetProperty(model.DisplayNoColumn);
                    var DisplayColumnPropInfo = type.GetProperty(model.DisplayColumn);

                    foreach (var itm in model.SortItems)
                    {
                        Items.Add(new SortModel
                        {
                            Id = Convert.ToInt64(IdColumnPropInfo.GetValue(itm, null)),
                            ColumnOrder = Converts.ToTryInt(DisplayNoColumnPropInfo.GetValue(itm, null)),
                            Description = Converts.ToTryString(DisplayColumnPropInfo.GetValue(itm, null))
                        });
                    }
                }
                return;
            }

            var where = @" WHERE 1 = 1 ";

            using (var utility = DbUtility.GetInstance())
            {
                if (!String.IsNullOrEmpty(model.OrganizationID))
                {
                    where += @" AND OrganizationID = ?OrganizationID ";
                    utility.AddParameter("OrganizationID", model.OrganizationID);
                }

                if (!String.IsNullOrEmpty(model.DisplayFlagColumn))
                {
                    where += String.Format(@" AND {0} = 1  ", model.DisplayFlagColumn);
                }

                if (!String.IsNullOrEmpty(model.StatusFlagColumn))
                {
                    where += String.Format(@" AND {0} = 0  ", model.StatusFlagColumn);
                }

                var sql = String.Format(@"
                        SELECT 
                            {0}
                          , {1}
                          , {2}
                        FROM 
                            {3}
                        {4}
                        ORDER BY
                            {2} ", model.IdColumn, model.DisplayColumn, model.DisplayNoColumn, model.TableName, where);

                var list = utility.ExecuteReader(sql);

                foreach (var item in list)
                {
                    Items.Add(new SortModel
                    {
                        Id = Convert.ToInt64(item[model.IdColumn]),
                        ColumnOrder = Converts.ToTryInt(item[model.DisplayNoColumn]),
                        Description = Converts.ToTryString(item[model.DisplayColumn])
                    });
                }
            }
        }

        public static SortListModel GetInstance()
        {
            return new SortListModel();
        }

        public void Update(SortTargetModel model, List<SortModel> items)
        {
            using (var utility = DbUtility.GetInstance())
            {
                utility.BeginTransaction();

                foreach (var item in items)
                {
                    var sql = String.Format(@"UPDATE {0} SET {1} = {2} WHERE {3} = {4}",
                        model.TableName, model.DisplayNoColumn, item.ColumnOrder + 1, model.IdColumn, item.Id);

                    utility.ExecuteNonQuery(sql);
                }

                utility.Commit();
            }
        }
    }
}

WebAppBase/WebAppBase/Models/Sorts/SortModel.cs
using SharedUtilitys.Models;

namespace WebAppBase.Models.Sorts
{
    public class SortModel : BaseModel
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public bool IsEnabled { get; set; }
        public int ColumnOrder { get; set; }
    }
}

WebAppBase/WebAppBase/Models/Sorts/SortParam.cs
namespace WebAppBase.Models.Sorts
{
    public class SortParam
    {
        public string TableName { get; set; }
        public string IdColumn { get; set; }
        public string NameColumn { get; set; }
    }
}

WebAppBase/WebAppBase/Controllers/Sorts/SortsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AspMvcLibrary.Attributes;
using WebAppBase.Configs;
using WebAppBase.Models.Base;
using WebAppBase.Models.Sorts;

namespace WebAppBase.Controllers
{
    [Authorize]
    public class SortsController : Controller
    {
        public ActionResult SortList()
        {
            var sortTargetModel = Session[SessionKeyConfig.SortTargetModel] as SortTargetModel;

            if (sortTargetModel == null)
            {
                throw new Exception("指定されたSession変数はISortModel型にCast出来ません。");
            }

            var model = new SortListModel(sortTargetModel);
            return View(model);
        }

        [HttpPost]
        [ActionName("SortList")]
        [SubmitCommand("back")]
        public ActionResult Back()
        {
            var model = _getTarget();
            return RedirectToAction(model.RedirectAction, model.RedirectController,model.RouteValues);
        }

        [HttpPost]
        public ActionResult Update(List<SortModel> items)
        {
            var model = _getTarget();
            if (items != null && items.Count > 0)
            {
                SortListModel.GetInstance().Update(model, items);
            }
            return Json(new { redirectTo = Url.Action(model.RedirectAction, model.RedirectController, model.RouteValues) });
        }

        private SortTargetModel _getTarget()
        {
            var model = Session[SessionKeyConfig.SortTargetModel] as SortTargetModel;

            if (model == null)
            {
                throw new Exception("SortTargetが指定されていません。");
            }

            return model;
        }
    }
}

WebAppBase/WebAppBase/Views/Sorts/SortList.cshtml
@using WebAppBase.App_GlobalResources
@model WebAppBase.Models.Sorts.SortListModel

@{
    ViewBag.Title = "SortList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    $(function () {
        $("#sortable").sortable();
        $("#sortable").disableSelection();
        $("#save-view-preferences").click(update);
    });

    function update() {
        var userPreferenceDetails = new Array();
        $("#sortable li").each(function (index) {
            var userPreferenceItem = new Object();
            //2014年11月05日　李軍　修正 Start
            userPreferenceItem.Id = $(this).find(".ItemId").val();
            userPreferenceItem.Id = $(this).find("div input").val();
            //End
            userPreferenceItem.IsEnabled = $(this).find($(".EnabledFlag")).attr("checked") == "checked" ? true : false;
            userPreferenceItem.ColumnOrder = index;
            userPreferenceDetails.push(userPreferenceItem);
        });
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Update", "Sorts")',
            data: JSON.stringify(userPreferenceDetails),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            success: function (result) {
                window.location.href = result.redirectTo;
            }
        });
    }

</script>

@using (Html.BeginForm())
{
    <h3>表示順の変更</h3>

    <div id="button_group">
        @if (Model.Items != null && Model.Items.Count > 0) { 
        <input type="submit" id="save-view-preferences" style="width:80px" value="@LanguageResource.CmdRegister" />
        }
        <input type="submit" name="back" style="width:80px" value="@LanguageResource.CmdBack" />
    </div>
           
    <div id="container_group">
        <div id="modify-view-elements" style="margin: 20px;">
            <ul id="sortable">
                @foreach (var m in Model.Items)
                {
                    <li><span id="sort-updown"></span>
                        <div id="container_sort">
                            @m.Description
                            @Html.Hidden("hdnId-" + m.Id, m.Id)
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
}
    